[package]
name = "drive-ocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.67"
camino = { version = "1.1.4", features = ["serde", "serde1"] }
clap = { version = "4.1.11", features = ["derive", "env"] }
color-eyre = "0.6.2"
dotenvy = { version = "0.15.6", features = ["clap"] }
futures-util = "0.3.27"
google-drive3 = "5.0.2"
hex = "0.4.3"
hmac = "0.12.1"
jwt = "0.16.0"
lazy_static = "1.4.0"
mime = "0.3.16"
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.11.0", features = ["metrics"] }
opentelemetry-semantic-conventions = "0.10.0"
redis = { version = "0.22.3", features = ["tokio", "aio", "tokio-comp"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["stream", "rustls-tls"], default-features=false }
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
sha2 = "0.10.6"
tempfile = "3.4.0"
test-case = "3.0.0"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full"] }
tokio-util = "0.7.7"
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-opentelemetry = { version = "0.18.0", features = ["metrics"] }
tracing-subscriber = { version = "0.3.16", features = ["fmt", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.0", features = ["v7", "serde"] }
warp = "0.3.3"

[dev-dependencies]
prettydiff = "0.6.2"
strsim = "0.10.0"
