[package]
name = "drive-ocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-channel = "1.8.0"
async-trait = "0.1.68"
camino = { version = "1.1.4", features = ["serde", "serde1"] }
clap = { version = "4.3.1", features = ["derive", "env"] }
color-eyre = "0.6.2"
dotenvy = { version = "0.15.7", features = ["clap"] }
futures-util = "0.3.28"
google-drive3 = "5.0.2"
hex = "0.4.3"
hmac = "0.12.1"
jwt = "0.16.0"
lazy_static = "1.4.0"
mime = "0.3.17"
opentelemetry = { version = "0.19.0", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.12.0", features = ["metrics"] }
opentelemetry-semantic-conventions = "0.11.0"
redis = { version = "0.23.0", features = ["tokio", "aio", "tokio-comp"] }
regex = "1.8.3"
reqwest = { version = "0.11.18", features = ["stream", "rustls-tls"], default-features=false }
rsmq_async = "5.1.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sha2 = "0.10.6"
tempfile = "3.5.0"
test-case = "3.1.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = "0.7.8"
tracing = "0.1.38"
tracing-error = "0.2.0"
tracing-opentelemetry = { features = ["metrics"], git = "https://github.com/jaysonsantos/tracing-opentelemetry", branch = "update-opentelemetry-0.19" }
tracing-subscriber = { version = "0.3.17", features = ["fmt", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.3", features = ["v7", "serde"] }
warp = "0.3.5"

[dev-dependencies]
prettydiff = "0.6.4"
strsim = "0.10.0"

[build-dependencies]
chrono = "0.4.26"
