name: Rust Build and Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v4
        with:
          context: .github
          push: true
          tags: ghcr.io/jaysonsantos/drive-ocr:builder
          cache-from: type=registry,ref=ghcr.io/jaysonsantos/drive-ocr:cache-builder
          cache-to: type=registry,ref=ghcr.io/jaysonsantos/drive-ocr:cache-builder
  build:
    runs-on: ubuntu-latest
    needs:
      - build-image
    container:
      image: ghcr.io/jaysonsantos/drive-ocr:builder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test
      - name: Build binaries
        run: |
          make copy-all-targets
      - name: Build
        run: |
          DOCKER_VERSION=$(echo $GITHUB_REF | sed -e 's|.*/||')
          make build-docker \
            DOCKER_VERSION=$DOCKER_VERSION \
            GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            GITHUB_USER="${{ github.actor }}"
